### ISSUE TITLE
Complex Type example

### ISSUE THREAD

**Issue by robomatic** [daniele-zurico/apollo2-subscriptions-how-to#2]
Thanks for your work on this. Can you give an example of how you would accomplish in your app structure?

```
gql`Post {
    author: Author
}`
```

**Comment by daniele-zurico** [comment]
can you better clarify you question please? not sure I understood

**Comment by robomatic** [comment]
From the gql statement above I'm using a Author type for Post.author. I don't know if it is the typescript that is preventing me from having this gql type on the Post.author or what. I tried importing the Author type to the Post type but it errors complaining Author type definition is missing.

**Comment by daniele-zurico** [comment]
still not sure i got properly the question but probably you looking to something like that:

```
// comment.js
const Comment = `
  type Comment {
    id: Int!
    message: String
    author: String
  }
`;

export default Comment;
```

```js
// post.js
import Comment from './comment';

const Post = `
  type Post {
    id: Int!
    title: String
    content: String
    author: String
    comments: [Comment]
  }
`;

export default [Post, Comment];
```

**Comment by chrischen** [comment]
Is this still the current best practice, or is simply supplying concatenated typeDefs? The apollo-server 2 migration guide seems to suggest that mergeSchemas and makeExecutableSchemas are "backwards compatible."
https://www.apollographql.com/docs/apollo-server/migration-two-dot.html#existing-schema

What is the advantage to splitting app models into separate schemas over just use "extend type ..." and merging the typeDefs into a single string?

**Comment by chrischen** [comment]
I got this response from Martijn Walraven of the Apollo team.

> schema stitching is never a good idea if you’re building a single server, because `mergeSchemas()` creates unnecessary runtime overhead and has many restrictions. you would only want to use that if you were merging schemas from different servers. if what you’re asking is how you can best modularize your schema, there are a number of options. the traditional way is to call `makeExecutableSchema()` with an array of type defs. that works, but you’ll still be responsible for merging the resolver maps yourself. with apollo server 2.2, we’ve started moving to a model where schema modules can be defined independently and will be merged automatically. an early version is available by passing in `modules` to `ApolloServer` (but not yet documented), and the evolution of this will become a focus point of apollo server 3.

So it seems like the best practice for data models for your local app to not be merged. This will also solve the referencing problem without needing to do any imports.

**Comment by robomatic** [comment]
Thanks Chris, that does give some helpful additional detail I could use. Closing as my original issue was resolved.
